[app]
title = Image to PDF Converter
package.name = imagetopdf
package.domain = org.example
source.dir = .
source.include_exts = py,png,jpg,kv atlas
requirements = python3,kivy==2.0.0,kivymd==0.104.1,pillow==8.4.0,jpeg,png,img2pdf==0.4.4,plyer==1.6.0
android.api = 30
android.minapi = 21
android.ndk_version = 21b
android.sdkmanager_additional_packages = ndk;ndk-sysimg;ndk-sysroot;extra-ndk-sysroot;extra-google-google_play_services;extra-google-m2repository;extra-google-android_tv_addon;extra-google-gcm;extra-google-cloud_tv_addon;extra-google-cloud_data_addon;extra-google-cloud_printing;extra-google-cloud_platform;extra-intel-intel_haxm;extra-intel-system_image;extra-m2repository;extra-ndk;sources-for-android-30;sources-for-android-29;sources-for-android-28;sources-for-android-27;sources-for-android-26;sources-for-android-25;sources-for-android-24;sources-for-android-23;sources-for-android-22;sources-for-android-21;sources-for-android-19;sources-for-android-18;sources-for-android-17;sources-for-android-16;sources-for-android-15;sources-for-android-14;sources-for-android-10;sources-for-android-9;sources-for-android-8;sources-for-android-7;addon-google_apis-google-30;addon-google_apis-google-29;addon-google_apis-google-28;addon-google_apis-google-27;addon-google_apis-google-26;addon-google_apis-google-25;addon-google_apis-google-24;addon-google_apis-google-23;addon-google_apis-google-22;addon-google_apis-google-21;addon-google_apis-google-19;addon-google_apis-google-18;addon-google_apis-google-17;addon-google_apis-google-16;addon-google_apis-google-15;addon-google_apis-google-14;addon-google_apis-google-10;addon-google_apis-google-9;addon-google_apis-google-8;addon-google_apis-google-7;addon-google_apis-google-6;build-tools;build-tools-30.0.3;build-tools-30.0.2;build-tools-30.0.1;build-tools-29.0.3;build-tools-29.0.2;build-tools-29.0.1;build-tools-28.0.3;build-tools-28.0.2;build-tools-28.0.1;build-tools-27.0.3;build-tools-27.0.2;build-tools-27.0.1;build-tools-26.0.3;build-tools-26.0.2;build-tools-26.0.1;build-tools-25.0.3;build-tools-25.0.2;build-tools-25.0.1;build-tools-24.0.3;build-tools-24.0.2;build-tools-24.0.1;build-tools-23.0.3;build-tools-23.0.2;build-tools-23.0.1;build-tools-21.1.2;build-tools-19.1.0;platform-tools;platforms;platforms-android-30;platforms-android-29;platforms-android-28;platforms-android-27;platforms-android-26;platforms-android-25;platforms-android-24;platforms-android-23;platforms-android-22;platforms-android-21;platforms-android-19;platforms-android-18;platforms-android-17;platforms-android-16;platforms-android-15;platforms-android-14;platforms-android-10;platforms-android-9;platforms-android-8;platforms-android-7
android.gradle_packages = com.android.tools.build:gradle:4.1.0
android.sdkmanager_from_source = True
android.ndk_from_source = True
android.sdkmanager_bin = /usr/local/bin/sdkmanager
android.ndk_bin = /usr/local/bin/ndk-build
android.sdkmanager_requirements = python3,jdk
android.ndk_requirements = python3,jdk
android.timeout_build = 10000
android.arch = armeabi-v7a arm64-v8a x86 x86_64
android.num_cores = 4
android.manifest_template = ./AndroidManifest.xml
android.java_source = ./src/main/java
android.java_package = org.example
android.java_libraries = ./libs/*.jar
android.aar_libraries = ./libs/*.aar
android.gradle_libraries = ./libs/*.gradle
android.gradle_plugins = ./gradle_plugins/*.gradle
android.gradle_properties = ./gradle.properties
android.gradlew = ./gradlew
android.gradlew_args = assembleDebug assembleRelease
android.gradlew_args_debug = assembleDebug
android.gradlew_args_release = assembleRelease
android.gradlew_args_test = assembleDebugAndroidTest assembleReleaseAndroidTest
android.gradlew_args_test_debug = assembleDebugAndroidTest
android.gradlew_args_test_release = assembleReleaseAndroidTest
android.gradlew_args_test_all = assembleDebugAndroidTest assembleReleaseAndroidTest
android.gradlew_args_test_all_debug = assembleDebugAndroidTest
android.gradlew_args_test_all_release = assembleReleaseAndroidTest
android.gradlew_args_test_all_debug_release = assembleDebugAndroidTest assembleReleaseAndroidTest
android.gradlew_args_test_all_debug_test = assembleDebugAndroidTest
android.gradlew_args_test_all_release_test = assembleReleaseAndroidTest
android.gradlew_args_test_all_debug_test_release = assembleDebugAndroidTest assembleReleaseAndroidTest
android.gradlew_args_test_all_debug_test_debug = assembleDebugAndroidTest
android.gradlew_args_test_all_release_test_debug = assembleReleaseAndroidTest
android.gradlew_args_test_all_debug_test_release_debug = assembleDebugAndroidTest assembleReleaseAndroidTest
android.gradlew_args_test_all_debug_test_release_release = assembleDebugAndroidTest assembleReleaseAndroidTest
android.gradlew_args_test_all_debug_test_debug_release = assembleDebugAndroidTest assembleReleaseAndroidTest
android.gradlew_args_test_all_release_test_debug_release = assembleReleaseAndroidTest assembleDebugAndroidTest
android.gradlew_args_test_all_debug_test_release_debug_release = assembleDebugAndroidTest assembleReleaseAndroidTest assembleDebugAndroidTest assembleReleaseAndroidTest
android.gradlew_args_test_all_debug_test_release_release_debug = assembleDebugAndroidTest assembleReleaseAndroidTest assembleDebugAndroidTest assembleReleaseAndroidTest
android.gradlew_args_test_all_debug_test_debug_release_debug = assembleDebugAndroidTest assembleReleaseAndroidTest assembleDebugAndroidTest assembleReleaseAndroidTest
android.gradlew_args_test_all_release_test_debug_release_debug = assembleReleaseAndroidTest assembleDebugAndroidTest assembleDebugAndroidTest assembleReleaseAndroidTest
android.gradlew_args_test_all_debug_test_release_debug_release_debug = assembleDebugAndroidTest assembleReleaseAndroidTest assembleDebugAndroidTest assembleReleaseAndroidTest assembleDebugAndroidTest assembleReleaseAndroidTest
android.gradlew_args_test_all_release_test_release_debug_release_debug = assembleReleaseAndroidTest assembleDebugAndroidTest assembleDebugAndroidTest assembleReleaseAndroidTest assembleDebugAndroidTest assembleReleaseAndroidTest
android.gradlew_args_test_all_debug_test_release_release_debug_release_debug = assembleDebugAndroidTest assembleReleaseAndroidTest assembleDebugAndroidTest assembleReleaseAndroidTest assembleDebugAndroidTest assembleReleaseAndroidTest assembleDebugAndroidTest assembleReleaseAndroidTest
android.gradlew_args_test_all_release_test_debug_release_debug_release_debug = assembleReleaseAndroidTest assembleDebugAndroidTest assembleDebugAndroidTest assembleReleaseAndroidTest assembleDebugAndroidTest assembleReleaseAndroidTest assembleDebugAndroidTest assembleReleaseAndroidTest
android.gradlew_args_test_all_debug_test_debug_release_debug_release_debug =

[android]
permissions = INTERNET
