name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install pip<24.1
        run: python -m pip install "pip<24.1"
      - name: Install dependencies
        run: |
          pip install buildozer cython==0.29.19 virtualenv==20.4.3 kivy==2.0.0 kivymd==0.104.1 pillow==8.4.0 img2pdf plyer==1.6.0
      - name: Build APK
        run: |
          buildozer init
          buildozer android debug
