name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install pip<24.1
        run: python -m pip install "pip<24.1"
      - name: Install dependencies
        run: |
          pip install buildozer cython==0.29.19 virtualenv==20.4.3 kivy==2.0.0 kivymd==0.104.1 pillow==8.4.0 img2pdf plyer==1.4.3
      - name: Set up Java (for Android SDK)
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Install Android SDK
        run: |
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O android-sdk.zip
          unzip -q android-sdk.zip -d android-sdk
          echo "ANDROID_SDK_ROOT=$(pwd)/android-sdk" >> $GITHUB_ENV
          echo "PATH=$(pwd)/android-sdk/cmdline-tools/bin:$PATH" >> $GITHUB_ENV
      - name: Accept SDK Licenses and Install Build-Tools
        run: |
          yes | android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$(pwd)/android-sdk "platforms;android-30" "build-tools;30.0.3"
      - name: Build APK
        run: |
          buildozer init
          buildozer android debug
