name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install pip<24.1
        run: python -m pip install "pip<24.1"
      - name: Install dependencies
        run: |
          pip install buildozer cython==0.29.19 virtualenv==20.4.3 kivy==2.0.0 kivymd==0.104.1 pillow==8.4.0 img2pdf plyer==1.4.3
      - name: Set up Java (for Android SDK)
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Install Android SDK
        run: |
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O android-sdk.zip
          unzip -q android-sdk.zip -d $HOME/android-sdk
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv $HOME/android-sdk/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/ 2>/dev/null || true
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
      - name: Accept SDK Licenses and Install Build-Tools
        run: |
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses --sdk_root=$HOME/android-sdk
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platforms;android-30" "build-tools;30.0.3"
          ls $HOME/android-sdk/build-tools/30.0.3 || echo "Build-tools not found!"
      - name: Debug Build-Tools Location
        run: |
          echo "Checking Build-Tools directory:"
          ls -la $HOME/android-sdk/build-tools/30.0.3
          echo "Checking for aidl:"
          find $HOME/android-sdk -name "aidl"
      - name: Build APK
        env:
          ANDROIDSDK: "$HOME/android-sdk"
          ANDROID_HOME: "$HOME/android-sdk"
          ANDROID_SDK_ROOT: "$HOME/android-sdk"
        run: |
          buildozer init
          buildozer android debug --sdk_dir $HOME/android-sdk --verbose
